import { run } from '../../lib/chatgpt/index.js';

export const anonymizeMethod = {
  STRICT: 'strict',
  BALANCED: 'balanced',
  LIGHT: 'light',
};

const METHODS = Object.values(anonymizeMethod);

const validateInput = (input) => {
  if (!input || typeof input !== 'object') {
    throw new Error('Input must be an object');
  }

  const { text, method, context } = input;

  if (!text || typeof text !== 'string') {
    throw new Error('Input must include a text string');
  }

  if (!method || !METHODS.includes(method)) {
    throw new Error(`Method must be one of: ${METHODS.join(', ')}`);
  }

  if (context !== undefined && typeof context !== 'string') {
    throw new Error('Context must be a string if provided');
  }

  return { text, method, context };
};

const stage1Prompt = (text, context) => `
Remove Distinctive Content and Markers
 - Identify and replace every distinctive or uncommon word, phrase, or sentence structure with the most widely used, nondescript alternative.
 - Remove all idioms, metaphors, analogies, cultural references, personal perspectives, and subjective tones.
 - Eliminate any explicit or implicit references to the author's identity, background, education, expertise, region, or intent.

${context ? `Context: ${context}\n` : ''}
Text to process:
${text}

Return ONLY the processed text, with no explanations or additional content.`;

const stage2Prompt = (text, context) => `
Normalize Structure, Formatting, and Tone
 - Restructure sentences and paragraphs to strictly follow standard, average patterns in length, order, and construction. Avoid any distinctive rhythm, complexity, or flow.
 - Uniformly normalize punctuation, formatting, and paragraphing; avoid any variation or emphasis that could signal style.
 - Strip out all emotional, evaluative, or expressive language, enforcing a neutral, impersonal, and objective tone.

 ${context ? `Context: ${context}\n` : ''}
 Text to process:
${text}

Return ONLY the normalized text, with no explanations or additional content.`;

const stage3Prompt = (text, context) => `
Stage 3: Suppress Latent Stylistic Patterns
 - Review for and suppress any recurring linguistic patterns, syntactic habits, or structural quirks—even if they appear common.
 - For all possible ways to phrase content, always select the plainest, most generic, and least distinctive form.
 - Ensure the final text reads as if generated by an automated system, with no evidence of personality, emotion, region, or any unique authorial traits.

 ${context ? `Context: ${context}\n` : ''}
Text to process:
${text}

Return ONLY the final anonymized text, with no explanations or additional content.`;

const anonymize = async (input) => {
  const { text, method, context } = validateInput(input);

  // Stage 1: Remove distinctive content
  const stage1Result = await run(stage1Prompt(text, method, context), {
    modelOptions: { modelName: 'privateBase' },
  });

  if (method === anonymizeMethod.LIGHT) {
    return {
      text: stage1Result,
      stages: {
        distinctiveContentRemoved: stage1Result,
      },
    };
  }

  // Stage 2: Normalize structure and tone
  const stage2Result = await run(stage2Prompt(stage1Result, method), {
    modelOptions: { modelName: 'privateBase' },
  });

  if (method === anonymizeMethod.BALANCED) {
    return {
      text: stage2Result,
      stages: {
        distinctiveContentRemoved: stage1Result,
        structureNormalized: stage2Result,
      },
    };
  }

  // Stage 3: Suppress stylistic patterns
  const stage3Result = await run(stage3Prompt(stage2Result, method), {
    modelOptions: { modelName: 'privateBase' },
  });

  return {
    text: stage3Result,
    stages: {
      distinctiveContentRemoved: stage1Result,
      structureNormalized: stage2Result,
      patternsSuppressed: stage3Result,
    },
  };
};

export { anonymize };
export default anonymize;
