/**
 * Progress event system for chains and verblets.
 *
 * Three event kinds:
 *   kind: 'event'     — domain moments (emit)     — decisions, phase transitions, meaningful outcomes
 *   kind: 'operation' — execution progress (progress) — start/complete/batch bookkeeping
 *   kind: 'telemetry' — infrastructure metrics (metrics) — LLM calls, retries, model selection
 *
 * Trace context (OTel-aligned):
 *   traceId    — correlates all events from one top-level chain call (generated by nameStep)
 *   spanId     — identifies this emitter's lifecycle (chain:start → chain:complete)
 *   parentSpanId — the spanId of the calling chain (set by nameStep from parent config)
 *
 * Default export:
 *   createProgressEmitter(name, callback, options) → { start, emit, progress, metrics, complete, error, batch }
 *
 * Named export:
 *   scopePhase(callback, phase) — compose phase paths for sub-chain delegation
 *
 * Chain usage:
 *   const emitter = createProgressEmitter(name, runConfig.onProgress, runConfig);
 *   emitter.start();
 *   emitter.emit({ event: 'phase', phase: 'generating-specification' });
 *   emitter.progress({ event: 'start', totalItems: 50 });
 *   emitter.complete({ totalItems: 10 });
 *
 * Infrastructure usage:
 *   const emitter = createProgressEmitter('llm', onProgress);
 *   emitter.metrics({ event: 'llm:call', status: 'success' });
 *   emitter.measure({ metric: Metric.tokenUsage, tokenType: 'input', value: 100 });
 *   emitter.measure({ metric: Metric.tokenUsage, tokenType: 'output', value: 50 });
 *   emitter.measure({ metric: Metric.llmDuration, value: 1200 });
 */

import libraryVersion from '../version/index.js';
import { Kind, StatusCode, ChainEvent, OpEvent } from './constants.js';

/** Generate a random hex ID. 16 chars for spanId, 32 for traceId. */
function hexId(bytes) {
  const arr = new Uint8Array(bytes);
  (globalThis.crypto ?? {}).getRandomValues?.(arr);
  if (!arr.some(Boolean)) {
    // Fallback: no crypto available
    for (let i = 0; i < bytes; i++) arr[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(arr, (b) => b.toString(16).padStart(2, '0')).join('');
}

/** 32-hex-char trace ID (OTel convention: 16 bytes). */
export function traceId() {
  return hexId(16);
}

/** 16-hex-char span ID (OTel convention: 8 bytes). */
export function spanId() {
  return hexId(8);
}

/**
 * Safe event dispatch. Enriches with timestamp and progress ratio.
 * Spreads into a new object — never mutates the input.
 * No implicit kind — callers provide it.
 */
function send(callback, data) {
  if (!callback || typeof callback !== 'function') return;

  const event = { timestamp: new Date().toISOString(), ...data };

  if (event.totalItems > 0 && event.processedItems !== undefined) {
    event.progress = event.processedItems / event.totalItems;
  }

  try {
    callback(event);
  } catch {
    // Progress callbacks must not crash callers.
  }
}

/**
 * Create a progress emitter bound to a named operation.
 * Does not emit on construction — call start() explicitly.
 *
 * @param {string} name - Operation name (used as event.step)
 * @param {Function} [callback] - Progress callback
 * @param {Object} [options]
 * @param {string} [options.operation] - Composed operation path (from nameStep)
 * @param {Date} [options.now] - Start timestamp for duration calculation
 * @param {string} [options.traceId] - Trace correlation ID (propagated from nameStep)
 * @param {string} [options.spanId] - Span ID for this emitter's lifecycle
 * @param {string} [options.parentSpanId] - Span ID of the calling chain
 * @returns {{ start, emit, progress, metrics, complete, error, batch }}
 */
export default function createProgressEmitter(
  name,
  callback,
  { operation, now, traceId: tid, spanId: sid, parentSpanId: psid } = {}
) {
  const startTime = now;

  // Trace context — present on every event when available
  const trace = {};
  if (tid) trace.traceId = tid;
  if (sid) trace.spanId = sid;
  if (psid) trace.parentSpanId = psid;

  // Resource identity
  const resource = { libraryName: 'verblets', libraryVersion };

  const base = { step: name, operation, ...trace, ...resource };

  const emitter = {
    start() {
      send(callback, { kind: Kind.telemetry, ...base, event: ChainEvent.start });
    },

    emit(data = {}) {
      send(callback, { kind: Kind.event, ...base, ...data });
    },

    progress(data = {}) {
      send(callback, { kind: Kind.operation, ...base, ...data });
    },

    metrics(data = {}) {
      send(callback, { kind: Kind.telemetry, ...base, ...data });
    },

    /**
     * Emit a flat dimensional metric (OTel-style).
     * Each call produces one measurement with a metric name, value,
     * and attributes that dashboards can group-by.
     *
     * @param {{ metric: string, value: number, [key: string]: * }} data
     */
    measure(data = {}) {
      send(callback, { kind: Kind.telemetry, ...base, ...data });
    },

    complete(meta = {}) {
      const { durationMs: explicit, ...rest } = meta;
      const durationMs = explicit ?? (startTime ? Date.now() - startTime.getTime() : undefined);
      send(callback, {
        kind: Kind.telemetry,
        ...base,
        event: ChainEvent.complete,
        statusCode: StatusCode.ok,
        ...(durationMs !== undefined && { durationMs }),
        ...rest,
      });
    },

    error(err, meta = {}) {
      const { durationMs: explicit, ...rest } = meta;
      const durationMs = explicit ?? (startTime ? Date.now() - startTime.getTime() : undefined);
      send(callback, {
        kind: Kind.telemetry,
        ...base,
        event: ChainEvent.error,
        statusCode: StatusCode.error,
        ...(durationMs !== undefined && { durationMs }),
        error: { message: err.message, type: err.constructor?.name },
        ...rest,
      });
    },

    batch(totalItems) {
      let processedItems = 0;
      function done(count) {
        processedItems += count;
        done.count = processedItems;
        emitter.progress({
          event: OpEvent.batchComplete,
          totalItems,
          processedItems,
          batchSize: count,
        });
        return processedItems;
      }
      done.count = 0;
      return done;
    },
  };

  return emitter;
}

/**
 * Wrap a progress callback to compose phase paths for sub-chain delegation.
 * Returns undefined when callback is absent, preserving the null-callback convention.
 *
 * @param {Function} [callback] - Progress callback
 * @param {string} phase - Phase identifier (e.g. 'group:extraction')
 * @returns {Function|undefined}
 */
export function scopePhase(callback, phase) {
  if (!callback || typeof callback !== 'function') return undefined;
  return (event) => callback({ ...event, phase: event.phase ? `${phase}/${event.phase}` : phase });
}
