import callLlm from '../../lib/llm/index.js';
import retry from '../../lib/retry/index.js';
import { asXML } from '../../prompts/wrap-variable.js';
import buildInstructions from '../../lib/build-instructions/index.js';
import { debug } from '../../lib/debug/index.js';
import { resolveOption } from '../../lib/context/resolve.js';
import depersonalizeSpecSchema from './depersonalize-specification.json';

const SENSITIVE_LLM = { sensitive: true, good: true };

export const depersonalizeMethod = {
  STRICT: 'strict',
  BALANCED: 'balanced',
  LIGHT: 'light',
};

const METHODS = Object.values(depersonalizeMethod);

// ===== Instruction Builders =====

export const {
  mapInstructions,
  filterInstructions,
  reduceInstructions,
  findInstructions,
  groupInstructions,
} = buildInstructions({
  specTag: 'depersonalization-specification',
  defaults: {
    map: `Apply depersonalization to each text item and return the depersonalized version.`,
    filter: `Keep items that contain distinctive authorial markers above a moderate threshold.\n\nNote: This evaluates the original text's stylistic distinctiveness, then returns depersonalized versions of filtered items.`,
    find: `Select the item with the most distinctive authorial fingerprint.\n\nNote: This evaluates the original texts, then returns the depersonalized version of the selected item.`,
    group: `Group items by stylistic distinctiveness level (low/medium/high) based on the types of authorial markers they contain.`,
  },
  steps: {
    reduce: `Apply the reduce operation to combine text items, then depersonalize the final accumulated result.`,
    filter: `Evaluate each item's stylistic distinctiveness to determine which meet the filter criteria.`,
    find: `Analyze items to identify the one that best matches the selection criteria.`,
    group: `Analyze each item to determine its appropriate group based on depersonalization needs.`,
  },
  specIntro: {
    map: 'Apply this depersonalization specification to each item:',
    filter: 'For items that pass the filter, apply this depersonalization:',
    reduce: 'Apply this depersonalization to the final accumulated result:',
    find: 'Apply this depersonalization to the selected item:',
    group: 'Apply this depersonalization to items within each group:',
  },
  mapSuffix: {
    processing: 'Return the depersonalized text with any relevant metadata.',
    default: 'Return the depersonalized text.',
  },
});

// ===== Stage Prompts =====

const specBlock = (specification) =>
  specification ? `\n${asXML(specification, { tag: 'depersonalization-rules' })}\n` : '';

const stage1Prompt = (text, context, specification) => `
Remove Distinctive Content and Markers
 - Identify and replace every distinctive or uncommon word, phrase, or sentence structure with the most widely used, nondescript alternative.
 - Remove all idioms, metaphors, analogies, cultural references, personal perspectives, and subjective tones.
 - Eliminate any explicit or implicit references to the author's identity, background, education, expertise, region, or intent.
${specBlock(specification)}
${context ? `Context: ${context}\n` : ''}
Text to process:
${text}

Return ONLY the processed text, with no explanations or additional content.`;

const stage2Prompt = (text, context, specification) => `
Normalize Structure, Formatting, and Tone
 - Restructure sentences and paragraphs to strictly follow standard, average patterns in length, order, and construction. Avoid any distinctive rhythm, complexity, or flow.
 - Uniformly normalize punctuation, formatting, and paragraphing; avoid any variation or emphasis that could signal style.
 - Strip out all emotional, evaluative, or expressive language, enforcing a neutral, impersonal, and objective tone.
${specBlock(specification)}
 ${context ? `Context: ${context}\n` : ''}
 Text to process:
${text}

Return ONLY the normalized text, with no explanations or additional content.`;

const stage3Prompt = (text, context, specification) => `
Suppress Latent Stylistic Patterns
 - Review for and suppress any recurring linguistic patterns, syntactic habits, or structural quirks—even if they appear common.
 - For all possible ways to phrase content, always select the plainest, most generic, and least distinctive form.
 - Ensure the final text reads as if generated by an automated system, with no evidence of personality, emotion, region, or any unique authorial traits.
${specBlock(specification)}
 ${context ? `Context: ${context}\n` : ''}
Text to process:
${text}

Return ONLY the final depersonalized text, with no explanations or additional content.`;

// ===== Core Functions =====

async function runStages(
  text,
  { method, context, specification, llm, maxAttempts = 3, onProgress, abortSignal, ...options }
) {
  // Stage 1: Remove distinctive content
  const stage1Result = await retry(
    () =>
      callLlm(stage1Prompt(text, context, specification), {
        llm,
        ...options,
      }),
    {
      label: 'depersonalize stage 1',
      maxAttempts,
      onProgress,
      abortSignal,
    }
  );

  if (method === depersonalizeMethod.LIGHT) {
    return {
      text: stage1Result,
      stages: {
        distinctiveContentRemoved: stage1Result,
      },
    };
  }

  // Stage 2: Normalize structure and tone
  const stage2Result = await retry(
    () =>
      callLlm(stage2Prompt(stage1Result, context, specification), {
        llm,
        ...options,
      }),
    {
      label: 'depersonalize stage 2',
      maxAttempts,
      onProgress,
      abortSignal,
    }
  );

  if (method === depersonalizeMethod.BALANCED) {
    return {
      text: stage2Result,
      stages: {
        distinctiveContentRemoved: stage1Result,
        structureNormalized: stage2Result,
      },
    };
  }

  // Stage 3: Suppress stylistic patterns
  const stage3Result = await retry(
    () =>
      callLlm(stage3Prompt(stage2Result, context, specification), {
        llm,
        ...options,
      }),
    {
      label: 'depersonalize stage 3',
      maxAttempts,
      onProgress,
      abortSignal,
    }
  );

  return {
    text: stage3Result,
    stages: {
      distinctiveContentRemoved: stage1Result,
      structureNormalized: stage2Result,
      patternsSuppressed: stage3Result,
    },
  };
}

/**
 * Depersonalize text — remove authorial fingerprint and stylistic markers.
 *
 * @param {string} text - Text to depersonalize
 * @param {object} [options]
 * @param {string} [options.method='balanced'] - Depersonalization intensity (strict/balanced/light)
 * @param {string} [options.context] - Additional context for depersonalization
 * @param {string|object} [options.llm={ sensitive: true, good: true }] - LLM config (defaults to sensitive+good privacy model; override to control model routing)
 * @param {number} [options.maxAttempts=3] - Max retry attempts per stage
 * @param {function} [options.onProgress] - Progress callback
 * @param {AbortSignal} [options.abortSignal] - Abort signal
 * @returns {Promise<{ text: string, stages: object }>}
 */
// eslint-disable-next-line require-await
export default async function depersonalize(text, options = {}) {
  const { method: _method, context, llm = SENSITIVE_LLM, ...rest } = options;
  const method = resolveOption('method', options, 'balanced');

  if (llm === SENSITIVE_LLM) {
    debug(
      'depersonalize: using default llm { sensitive: true, good: true } — pass options.llm to override'
    );
  }

  if (!text || typeof text !== 'string') {
    throw new Error('Text must be a non-empty string');
  }

  if (!METHODS.includes(method)) {
    throw new Error(`Method must be one of: ${METHODS.join(', ')}`);
  }

  if (context !== undefined && typeof context !== 'string') {
    throw new Error('Context must be a string if provided');
  }

  return runStages(text, { method, context, llm, ...rest });
}

/**
 * Generate a depersonalization specification from instructions.
 *
 * Returns structured JSON via response_format — not free text.
 *
 * @param {string} instructions - Natural language depersonalization instructions
 * @param {object} [config]
 * @returns {Promise<{ method: string, preservationRules: string, removalTargets: string, consistencyGuidelines: string, contextNotes?: string }>}
 */
export async function depersonalizeSpec(instructions, config = {}) {
  const { llm = SENSITIVE_LLM, maxAttempts = 3, onProgress, abortSignal, ...rest } = config;

  if (llm === SENSITIVE_LLM) {
    debug(
      'depersonalizeSpec: using default llm { sensitive: true, good: true } — pass config.llm to override'
    );
  }

  const specSystemPrompt = `You are a depersonalization specification generator. Create a clear, structured specification for removing authorial fingerprints from text.`;

  const specUserPrompt = `Analyze these depersonalization instructions and generate a specification.

${asXML(instructions, { tag: 'depersonalization-instructions' })}

Provide a JSON object describing:
- method: The depersonalization intensity level (light, balanced, or strict)
- preservationRules: What content and characteristics to preserve
- removalTargets: What stylistic markers and patterns to remove
- consistencyGuidelines: How to maintain consistency across texts
- contextNotes: Any special handling requirements or context-specific notes`;

  const response = await retry(
    () =>
      callLlm(specUserPrompt, {
        llm,
        modelOptions: {
          systemPrompt: specSystemPrompt,
          response_format: {
            type: 'json_schema',
            json_schema: {
              name: 'depersonalize_specification',
              schema: depersonalizeSpecSchema,
            },
          },
        },
        ...rest,
      }),
    {
      label: 'depersonalize spec',
      maxAttempts,
      onProgress,
      abortSignal,
    }
  );

  return response;
}

/**
 * Apply a depersonalization specification to text.
 *
 * The specification is injected as XML into each stage prompt,
 * genuinely influencing the depersonalization behavior.
 *
 * @param {string} text - Text to depersonalize
 * @param {object} specification - Structured depersonalization specification
 * @param {object} [config]
 * @returns {Promise<{ text: string, stages: object }>}
 */
// eslint-disable-next-line require-await
export async function applyDepersonalize(text, specification, config = {}) {
  const { llm = SENSITIVE_LLM, ...rest } = config;

  if (llm === SENSITIVE_LLM) {
    debug(
      'applyDepersonalize: using default llm { sensitive: true, good: true } — pass config.llm to override'
    );
  }
  const method = specification.method || 'balanced';

  return runStages(text, { method, specification, llm, ...rest });
}

/**
 * Create a depersonalizer function with a baked-in specification.
 *
 * @param {object} specification - Structured depersonalization specification
 * @param {object} [config] - Default config for each call
 * @returns {Function} async (text) => result, with .specification property
 */
export function createDepersonalizer(specification, config = {}) {
  const depersonalizerFn = (text) => applyDepersonalize(text, specification, config);

  Object.defineProperty(depersonalizerFn, 'specification', {
    get() {
      return specification;
    },
    enumerable: true,
  });

  return depersonalizerFn;
}
